spring:
  application:
    name: hibernate-jpa
  # generic
  #jpa:
  #  show-sql: true
  # we will use application-local.yaml configuration
  profiles:
    active: local
  # init db using hibernate and  sql script
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        hbm2ddl:
          auto: validate
      defer-datasource-initialization: false
      datasource:
        # note: we made h2 compatible with mysql
        url: "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE"
        username: "sa"
        password: "password"
  # configuring h2 console
  # http://localhost:8080/h2-console
  h2:
    console:
      enabled: true
      path: /h2-console


# enable logging binded values
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE