spring:
  application:
    name: hibernate-jpa
  # we will use application-local.yaml configuration
  profiles:
    active: local

  datasource:
    password: password
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: sa
  flyway:
    # org.springframework.dao.DataIntegrityViolationException: could not execute statement [NULL non permis pour la colonne "id"
    # NULL not allowed for column "id"; SQL statement

    locations: classpath:db/migration
    #locations: classpath:db/migration/common
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database: mysql
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
        #hbm2ddl:
        #  auto: validate


logging:
  level:
    org:
      flywaydb: DEBUG
      hibernate:
        type:
          descriptor:
            sql: trace
        # enable logging binded values
        orm:
          jdbc:
            bind: TRACE